application : unknownapp
runtime : python27
version : 1
api_version : 1
threadsafe : true

libraries:
- name: webapp2
  version: "latest"

handlers:

- url : /api/admin/config/.*
  script : main.api
  login : admin

- url : /api/.*
  script : main.api

- url : /(.*?\.)(js|css|eot|woff2|woff|ttf|jpg|png|svg|gif)
  static_files : static/\1\2
  upload : static/.*

- url : /.*
  static_files : static/index.html
  upload : static/index.html
