application : unknownapp
runtime : python27
version : 1
api_version : 1
threadsafe : true

libraries:
- name: webapp2
  version: "latest"

handlers:

- url : /api/admin/config/.*
  script : main.api
  login : admin

- url : /api/.*
  script : main.api
